version: "3.8"

services:
  semanticapp:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=pgvector
      - DB_PORT=5432
    depends_on:
      - pgvector
      - duckling

  pgvector:
    image: ankane/pgvector
    environment:
      - POSTGRES_USER=deeptech
      - POSTGRES_PASSWORD=deeptech
      - POSTGRES_DB=semanticdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  duckling:
    image: rasa/duckling
    ports:
      - "8000:8000"